<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <title>Titanic: Machine Learning from Disaster</title>
  <meta property="og:title" content="Titanic: Machine Learning from Disaster" />
  <meta name="twitter:title" content="Titanic: Machine Learning from Disaster" />
  <meta name="description" content="1 Introduction1.1 匯入資料 (Import Data)1.2 觀察資料外觀 (Data Overview)2 特徵工程 (Feature Engineering)2.1 Passenger Title2.2 Children vs. Women vs. Men2.3 Solo Travel vs. Group Travel3 遺漏值處理 (Impute Missing Value)4 訓練模型 (Training a Model)4.1 變數選擇 (Variable Selection)4.2 建立分類模型 (Building a Classification Model)4.3 變數的重要性 (Variable Importance)5 衡量模型表現 (Evaluating Model Performance)5.1 模型錯誤率 (Model Error)5.2 模型準確度 (Model Accuracy)5.">
  <meta property="og:description" content="1 Introduction1.1 匯入資料 (Import Data)1.2 觀察資料外觀 (Data Overview)2 特徵工程 (Feature Engineering)2.1 Passenger Title2.2 Children vs. Women vs. Men2.3 Solo Travel vs. Group Travel3 遺漏值處理 (Impute Missing Value)4 訓練模型 (Training a Model)4.1 變數選擇 (Variable Selection)4.2 建立分類模型 (Building a Classification Model)4.3 變數的重要性 (Variable Importance)5 衡量模型表現 (Evaluating Model Performance)5.1 模型錯誤率 (Model Error)5.2 模型準確度 (Model Accuracy)5.">
  <meta name="twitter:description" content="1 Introduction1.1 匯入資料 (Import Data)1.2 觀察資料外觀 (Data Overview)2 特徵工程 (Feature Engineering)2.1 Passenger Title2.2 Children vs. Women vs. Men2.3 Solo Travel vs. Group Travel3 遺漏值處理 (Impute …">
  <meta name="author" content="© Carol Chen"/>
  <link href='/img/favicon.ico' rel='icon' type='image/x-icon'/>
  <meta property="og:image" content="/img/me.jpg" />
  <meta name="twitter:image" content="/img/me.jpg" />
  <meta name="twitter:card" content="summary" />
  <meta property="og:url" content="/post/2017-12-28-titanic-machine-learning-from-disaster/" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Chia-Yin Chen" />

  <meta name="generator" content="Hugo 0.54.0" />
  <link rel="canonical" href="/post/2017-12-28-titanic-machine-learning-from-disaster/" />
  <link rel="alternate" href="" type="application/rss+xml" title="Chia-Yin Chen">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css" integrity="sha384-wITovz90syo1dJWVh32uuETPVEtGigN07tkttEqPv+uR2SE/mbQcG7ATL28aI9H0" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="/css/main.css" /><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" />
  <link rel="stylesheet" href="/css/highlighting.css" />
  <link rel="stylesheet" href="/css/pygment_highlights.css" />
  <link rel="stylesheet" href="/css/highlight.min.css" />




<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css" integrity="sha256-sCl5PUOGMLfFYctzDW3MtRib0ctyUvI9Qsmq2wXOeBY=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css" integrity="sha256-BFeI1V+Vh1Rk37wswuOYn5lsTcaU96hGaI7OUVCLjPc=" crossorigin="anonymous" />



<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

<div class="pswp__bg"></div>

<div class="pswp__scroll-wrap">
    
    <div class="pswp__container">
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
      <div class="pswp__item"></div>
    </div>
    
    <div class="pswp__ui pswp__ui--hidden">
    <div class="pswp__top-bar">
      
      <div class="pswp__counter"></div>
      <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
      <button class="pswp__button pswp__button--share" title="Share"></button>
      <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
      <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
      
      
      <div class="pswp__preloader">
        <div class="pswp__preloader__icn">
          <div class="pswp__preloader__cut">
            <div class="pswp__preloader__donut"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
      <div class="pswp__share-tooltip"></div>
    </div>
    <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
    </button>
    <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
    </button>
    <div class="pswp__caption">
      <div class="pswp__caption__center"></div>
    </div>
    </div>
    </div>
</div>

</head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Chia-Yin Chen</a>
    </div>

    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="nav navbar-nav navbar-right">
        
          
            <li>
              <a title="About" href="/page/about/">About</a>
            </li>
          
        
          
            <li>
              <a title="Blog" href="/">Blog</a>
            </li>
          
        
          
            <li>
              <a title="Tags" href="/tags">Tags</a>
            </li>
          
        

        

        
      </ul>
    </div>

    <div class="avatar-container">
      <div class="avatar-img-border">
        
          <a title="Chia-Yin Chen" href="/">
            <img class="avatar-img" src="/img/me.jpg" alt="Chia-Yin Chen" />
          </a>
        
      </div>
    </div>

  </div>
</nav>




    
  
  
  




  

  <header class="header-section ">
    
    <div class="intro-header no-img">
      
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-heading">
              <h1>Titanic: Machine Learning from Disaster</h1>
                
                
                  <span class="post-meta">
  <i class="fa fa-calendar-o"></i>&nbsp;Posted on December 28, 2017
  &nbsp;|&nbsp; <i class="fa fa-clock-o"></i> 16 min (3333 mots)
  
</span>


                
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>


    
<div class="container" role="main">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <article role="main" class="blog-post">
        

<div id="TOC">
<ul>
<li><a href="#introduction"><span class="toc-section-number">1</span> Introduction</a><ul>
<li><a href="#-import-data"><span class="toc-section-number">1.1</span> 匯入資料 (Import Data)</a></li>
<li><a href="#-data-overview"><span class="toc-section-number">1.2</span> 觀察資料外觀 (Data Overview)</a></li>
</ul></li>
<li><a href="#-feature-engineering"><span class="toc-section-number">2</span> 特徵工程 (Feature Engineering)</a><ul>
<li><a href="#passenger-title"><span class="toc-section-number">2.1</span> Passenger Title</a></li>
<li><a href="#children-vs.women-vs.men"><span class="toc-section-number">2.2</span> Children vs. Women vs. Men</a></li>
<li><a href="#solo-travel-vs.group-travel"><span class="toc-section-number">2.3</span> Solo Travel vs. Group Travel</a></li>
</ul></li>
<li><a href="#-impute-missing-value"><span class="toc-section-number">3</span> 遺漏值處理 (Impute Missing Value)</a></li>
<li><a href="#-training-a-model"><span class="toc-section-number">4</span> 訓練模型 (Training a Model)</a><ul>
<li><a href="#-variable-selection"><span class="toc-section-number">4.1</span> 變數選擇 (Variable Selection)</a></li>
<li><a href="#-building-a-classification-model"><span class="toc-section-number">4.2</span> 建立分類模型 (Building a Classification Model)</a></li>
<li><a href="#-variable-importance"><span class="toc-section-number">4.3</span> 變數的重要性 (Variable Importance)</a></li>
</ul></li>
<li><a href="#-evaluating-model-performance"><span class="toc-section-number">5</span> 衡量模型表現 (Evaluating Model Performance)</a><ul>
<li><a href="#-model-error"><span class="toc-section-number">5.1</span> 模型錯誤率 (Model Error)</a></li>
<li><a href="#-model-accuracy"><span class="toc-section-number">5.2</span> 模型準確度 (Model Accuracy)</a></li>
<li><a href="#roc--roc-curve"><span class="toc-section-number">5.3</span> ROC 曲線 (ROC Curve)</a></li>
</ul></li>
<li><a href="#making-our-prediction"><span class="toc-section-number">6</span> Making our prediction</a></li>
</ul>
</div>

<div id="introduction" class="section level1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>這份報告選擇了 Kaggle 的 Titanic 資料集，運用機器學習 (machine learning) 技術來預測鐵達尼號沉船後哪些乘客會存活下來。</p>
<div id="-import-data" class="section level2">
<h2><span class="header-section-number">1.1</span> 匯入資料 (Import Data)</h2>
<p>首先讀取 titanic 的<strong>訓練 train.csv </strong>與<strong>測試 test.csv </strong>資料，其中 test.csv 是一個沒有 Survived 答案的 csv 檔案。</p>
<pre class="r"><code># 資料讀取
titanic_train &lt;- read.csv(&quot;https://storage.googleapis.com/kaggle_titanic/train.csv&quot;)
titanic_test &lt;- read.csv(&quot;https://storage.googleapis.com/kaggle_titanic/test.csv&quot;)

# 新增 `Set` 變數來分辨訓練與測試資料
titanic_train$Set &lt;- &quot;Train&quot;
titanic_test$Set &lt;- &quot;Test&quot;

# 合併訓練與測試資料
titanic_test$Survived &lt;- NA
full_data &lt;- rbind(titanic_train, titanic_test)</code></pre>
</div>
<div id="-data-overview" class="section level2">
<h2><span class="header-section-number">1.2</span> 觀察資料外觀 (Data Overview)</h2>
<pre class="r"><code>str(full_data) # The structure of titanic dataset</code></pre>
<pre><code>## &#39;data.frame&#39;:    1309 obs. of  13 variables:
##  $ PassengerId: int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Survived   : int  0 1 1 1 0 0 0 0 1 1 ...
##  $ Pclass     : int  3 1 3 1 3 3 1 3 3 2 ...
##  $ Name       : Factor w/ 1307 levels &quot;Abbing, Mr. Anthony&quot;,..: 109 191 358 277 16 559 520 629 417 581 ...
##  $ Sex        : Factor w/ 2 levels &quot;female&quot;,&quot;male&quot;: 2 1 1 1 2 2 2 2 1 1 ...
##  $ Age        : num  22 38 26 35 35 NA 54 2 27 14 ...
##  $ SibSp      : int  1 1 0 1 0 0 0 3 0 1 ...
##  $ Parch      : int  0 0 0 0 0 0 0 1 2 0 ...
##  $ Ticket     : Factor w/ 929 levels &quot;110152&quot;,&quot;110413&quot;,..: 524 597 670 50 473 276 86 396 345 133 ...
##  $ Fare       : num  7.25 71.28 7.92 53.1 8.05 ...
##  $ Cabin      : Factor w/ 187 levels &quot;&quot;,&quot;A10&quot;,&quot;A14&quot;,..: 1 83 1 57 1 1 131 1 1 1 ...
##  $ Embarked   : Factor w/ 4 levels &quot;&quot;,&quot;C&quot;,&quot;Q&quot;,&quot;S&quot;: 4 2 4 4 4 3 4 4 4 2 ...
##  $ Set        : chr  &quot;Train&quot; &quot;Train&quot; &quot;Train&quot; &quot;Train&quot; ...</code></pre>
<p>得知 titanic 資料集有 1309 個觀測值與 13 個變數，<a href="https://www.kaggle.com/c/titanic/data">資料欄位說明</a>如下表：</p>
<table>
<thead>
<tr class="header">
<th align="left">Variable</th>
<th align="left">Definition</th>
<th align="left">Key</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">PassengerId</td>
<td align="left">分配給每個乘客的唯一編號</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Survived</td>
<td align="left">生存與否的指標</td>
<td align="left">0 = 死亡, 1 = 存活</td>
</tr>
<tr class="odd">
<td align="left">Pclass</td>
<td align="left">船票的艙等，代表社會經濟地位</td>
<td align="left">1 = Upper, 2 = Middle, 3 = Lower</td>
</tr>
<tr class="even">
<td align="left">Name</td>
<td align="left">乘客姓名</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Sex</td>
<td align="left">乘客性別</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Age</td>
<td align="left">乘客年齡 (單位：年)</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">SibSp</td>
<td align="left">乘客的兄弟姐妹或配偶在船上的人數</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Parch</td>
<td align="left">乘客的父母或孩子在船上的人數</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Ticket</td>
<td align="left">船票編號</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Fare</td>
<td align="left">船票價格</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Cabin</td>
<td align="left">乘客佔用的客艙號碼</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Embarked</td>
<td align="left">乘客登船的港口</td>
<td align="left">C = Cherbourg, Q = Queenstown, S = Southampton</td>
</tr>
<tr class="odd">
<td align="left">Set</td>
<td align="left">識別訓練與測試資料</td>
<td align="left"></td>
</tr>
</tbody>
</table>
<p>
</p>
<pre class="r"><code>summary(full_data) # The summary of titanic dataset</code></pre>
<pre><code>##   PassengerId      Survived          Pclass     
##  Min.   :   1   Min.   :0.0000   Min.   :1.000  
##  1st Qu.: 328   1st Qu.:0.0000   1st Qu.:2.000  
##  Median : 655   Median :0.0000   Median :3.000  
##  Mean   : 655   Mean   :0.3838   Mean   :2.295  
##  3rd Qu.: 982   3rd Qu.:1.0000   3rd Qu.:3.000  
##  Max.   :1309   Max.   :1.0000   Max.   :3.000  
##                 NA&#39;s   :418                     
##                                Name          Sex           Age       
##  Connolly, Miss. Kate            :   2   female:466   Min.   : 0.17  
##  Kelly, Mr. James                :   2   male  :843   1st Qu.:21.00  
##  Abbing, Mr. Anthony             :   1                Median :28.00  
##  Abbott, Mr. Rossmore Edward     :   1                Mean   :29.88  
##  Abbott, Mrs. Stanton (Rosa Hunt):   1                3rd Qu.:39.00  
##  Abelson, Mr. Samuel             :   1                Max.   :80.00  
##  (Other)                         :1301                NA&#39;s   :263    
##      SibSp            Parch            Ticket          Fare        
##  Min.   :0.0000   Min.   :0.000   CA. 2343:  11   Min.   :  0.000  
##  1st Qu.:0.0000   1st Qu.:0.000   1601    :   8   1st Qu.:  7.896  
##  Median :0.0000   Median :0.000   CA 2144 :   8   Median : 14.454  
##  Mean   :0.4989   Mean   :0.385   3101295 :   7   Mean   : 33.295  
##  3rd Qu.:1.0000   3rd Qu.:0.000   347077  :   7   3rd Qu.: 31.275  
##  Max.   :8.0000   Max.   :9.000   347082  :   7   Max.   :512.329  
##                                   (Other) :1261   NA&#39;s   :1        
##              Cabin      Embarked     Set           
##                 :1014    :  2    Length:1309       
##  C23 C25 C27    :   6   C:270    Class :character  
##  B57 B59 B63 B66:   5   Q:123    Mode  :character  
##  G6             :   5   S:914                      
##  B96 B98        :   4                              
##  C22 C26        :   4                              
##  (Other)        : 271</code></pre>
<p>觀察到 <strong>Age</strong> 變數有 263 個遺漏值，<strong>Fare</strong> 變數有 1 個遺漏值，<strong>Cabin</strong> 變數有 1014 個空值，<strong>Embarked</strong> 變數有 2 個空值，由於 Cabin 變數的空值太多了，因此在訓練模型時將不考慮加入此變數，其他 Age、Fare、Embarked 變數會在「遺漏值處理 (Impute Missing Value)」的小節進行遺漏值填補。</p>
</div>
</div>
<div id="-feature-engineering" class="section level1">
<h1><span class="header-section-number">2</span> 特徵工程 (Feature Engineering)</h1>
<p>有句話讓我印象很深刻：<strong>「數據和特徵決定了機器學習的上限，而模型和算法只是逼近這個上限而已」</strong>。為了讓我的預測模型 performance 更出色，我需要為我的預測模型獲取到更好的訓練特徵資料。</p>
<div id="passenger-title" class="section level2">
<h2><span class="header-section-number">2.1</span> Passenger Title</h2>
<p><strong>Name</strong> 變數的格式為：&quot; Surname (姓), Title (頭銜). Firstname (名)… “，可以從乘客姓名中將<a href="https://en.wikipedia.org/wiki/English_honorifics">頭銜 (Title)</a> 提取出來成為有意義的資訊。</p>
<pre class="r"><code># 自訂一個可以提取乘客 Title 的函數
get_Title &lt;- function(data) {
  title_start &lt;- regexpr(pattern = &quot;\\,[A-Za-z ]{1,20}\\.&quot;, data$Name)
  title_end &lt;- title_start + attr(title_start, &quot;match.length&quot;) - 1
  data$Title &lt;- substr(data$Name, start = title_start + 2, stop = title_end - 1)
  return(data$Title)
}

full_data$Title &lt;- get_Title(full_data)
# 列出 Title 類別數量
table(full_data$Title)</code></pre>
<pre><code>## 
##         Capt          Col          Don         Dona           Dr 
##            1            4            1            1            8 
##     Jonkheer         Lady        Major       Master         Miss 
##            1            1            2           61          260 
##         Mlle          Mme           Mr          Mrs           Ms 
##            2            1          757          197            2 
##          Rev          Sir the Countess 
##            8            1            1</code></pre>
<pre class="r"><code># 整理歸類及重新定義一些 Title
full_data$Title[full_data$Title %in% c(&quot;Capt&quot;, &quot;Col&quot;, &quot;Don&quot;, &quot;Dona&quot;, &quot;Dr&quot;, &quot;Major&quot;, &quot;Rev&quot;)] &lt;- &quot;Officer&quot; # 高層職位
full_data$Title[full_data$Title %in% c(&quot;Lady&quot;, &quot;the Countess&quot;, &quot;Sir&quot;, &quot;Jonkheer&quot;)] &lt;- &quot;Noble&quot; # 貴族、皇族
full_data$Title[full_data$Title == &quot;Mme&quot;] &lt;- &quot;Mrs&quot;  # 夫人、太太
full_data$Title[full_data$Title %in% c(&quot;Ms&quot;, &quot;Mlle&quot;)] &lt;- &quot;Miss&quot;  # 女士、小姐
full_data$Title &lt;- factor(full_data$Title)

# 列出整理過後的 Title 類別數量
table(full_data$Title)</code></pre>
<pre><code>## 
##  Master    Miss      Mr     Mrs   Noble Officer 
##      61     264     757     198       4      25</code></pre>
<pre class="r"><code># 視覺化 `Title` 與 `Survived` 之間的關係
library(ggplot2)
ggplot(full_data[full_data$Set == &quot;Train&quot;, ], aes(x = Title, fill = factor(Survived))) +
  geom_bar(stat = &quot;count&quot;, position = &quot;dodge&quot;) +
  xlab(&quot;Title&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Passenger Survival Counts by Title&quot;) +
  theme(legend.position = &quot;right&quot;,
        plot.title = element_text(size = 15, hjust = 0.5)) +
  scale_fill_discrete(guide = guide_legend(title = &quot;survived&quot;),
                      labels = c(&quot;NO&quot;, &quot;YES&quot;)) +
  geom_text(stat = &quot;count&quot;, aes(label = ..count..),
            position = position_dodge(width = 0.9), vjust = -0.25, size = 3)</code></pre>
<p><img src="/post/2017-12-28-Titanic-Machine-Learning-from-Disaster_files/figure-html/unnamed-chunk-5-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>可觀察到 Title 為 <strong>Miss</strong> 和 <strong>Mrs</strong> 存活的機會比較大，Title 為 <strong>Mr</strong> 的存活機會明顯小很多，也間接告訴我們男性倖存者明顯少於女性。</p>
</div>
<div id="children-vs.women-vs.men" class="section level2">
<h2><span class="header-section-number">2.2</span> Children vs. Women vs. Men</h2>
<pre class="r"><code># 視覺化 `Age` 在不同的 `Sex` 中與 `Survived` 之間的關係
ggplot(full_data[full_data$Set == &quot;Train&quot;, ], aes(x = Age, fill = factor(Survived))) +
  geom_histogram() +
  facet_wrap(~ Sex) +
  xlab(&quot;Age&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Passenger Survival Counts by Age and Sex&quot;) +
  theme(legend.position = &quot;right&quot;,
        plot.title = element_text(size = 15, hjust = 0.5)) +
  scale_fill_discrete(guide = guide_legend(title = &quot;survived&quot;),
                      labels = c(&quot;NO&quot;, &quot;YES&quot;))</code></pre>
<p><img src="/post/2017-12-28-Titanic-Machine-Learning-from-Disaster_files/figure-html/unnamed-chunk-6-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>視覺化明顯告訴我們不論在哪個年齡階段女性的存活機會都比較高，並可觀察到不論是在男性還是女性，15 歲以下的孩童存活機會都比較高。因此決定以 15 歲來區分孩童及成人對 <strong>Survived</strong> 的影響。</p>
<pre class="r"><code># 建立新的變數 `Child` ，辨識 &quot;孩童&quot;、&quot;成人&quot;
full_data$Child[full_data$Age &lt; 15] &lt;- &quot;Child&quot;
full_data$Child[full_data$Age &gt;= 15] &lt;- &quot;Adult&quot;
full_data$Child &lt;- factor(full_data$Child)</code></pre>
<p>鐵達尼號逃生時究竟是老弱婦孺優先上救生艇？還是有錢人先上救生艇？</p>
<pre class="r"><code># 建立新的變數 `identity`，辨識 &quot;男性孩童&quot;、&quot;女性孩童&quot;、&quot;男性成人&quot;、&quot;女性成人&quot;
full_data$identity[full_data$Age &gt;= 15 &amp; full_data$Sex == &quot;male&quot;] &lt;- &quot;Man&quot;
full_data$identity[full_data$Age &gt;= 15 &amp; full_data$Sex == &quot;female&quot;] &lt;- &quot;Woman&quot;
full_data$identity[full_data$Age &lt; 15 &amp; full_data$Sex == &quot;male&quot;] &lt;- &quot;Boy&quot;
full_data$identity[full_data$Age &lt; 15 &amp; full_data$Sex == &quot;female&quot;] &lt;- &quot;Girl&quot;
full_data$identity &lt;- factor(full_data$identity)

# 視覺化 `identity` 在不同的 `Pclass` 中與 `Survived` 之間的關係
full_data$Pclass &lt;- factor(full_data$Pclass)
ggplot(full_data[full_data$Set == &quot;Train&quot; &amp; !is.na(full_data$Age), ],
       aes(x = identity, fill = factor(Survived))) +
  geom_bar(stat = &quot;count&quot;, position = &quot;dodge&quot;) +
  facet_wrap(~ Pclass, labeller = label_both) +
  xlab(&quot;Identity&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Passenger Survival Counts by Identity and Pclass&quot;) +
  theme(legend.position = &quot;right&quot;,
        plot.title = element_text(size = 15, hjust = 0.5)) +
  scale_fill_discrete(guide = guide_legend(title = &quot;survived&quot;),
                      labels = c(&quot;NO&quot;, &quot;YES&quot;)) +
  geom_text(stat = &quot;count&quot;, aes(label = ..count..),
            position = position_dodge(width = 0.9), vjust = -0.25, size = 3)</code></pre>
<p><img src="/post/2017-12-28-Titanic-Machine-Learning-from-Disaster_files/figure-html/unnamed-chunk-8-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>註：【1】Boy：age &lt; 15 &amp; Sex == “male”【2】Girl：age &lt; 15 &amp; Sex == “female”【3】Man：Age &gt;= 15 &amp; Sex == “male”【4】Woman：Age &gt;= 15 &amp; Sex == “female”</p>
<p>視覺化顯示確實和電影演的一樣，逃生時婦女兒童優先上救生艇，大量的孩童和女性都存活了下來。但也發現到一個殘酷的事實，雖然船長發出了婦女和兒童優先上救生艇的口號，但逃生的機會還是取決於乘客當時所在的艙等，可發現Pclass = 3 (Lower艙等) 的乘客不管是孩童還是成人存活的機會都不高，Pclass = 1 (Upper艙等) 和Pclass = 2 (Middle艙等) 存活的機會高了些，所以其實只是 Upper 艙等和 Middle 艙等的婦女和兒童優先而已，間接說明了有錢人還是比窮人先活下來了…</p>
</div>
<div id="solo-travel-vs.group-travel" class="section level2">
<h2><span class="header-section-number">2.3</span> Solo Travel vs. Group Travel</h2>
<p><strong>SibSp</strong> (兄弟姐妹或配偶在船上的人數) 及 <strong>Parch</strong> (直系的親人在船上的人數) 這兩個變數包含了有關乘客家庭的隱藏資訊，利用這兩個變數製作一個新的變數叫作 <strong>family_size</strong> (家庭人口大小)。</p>
<pre class="r"><code># 建立新的變數 `family_size`，包括乘客本人
full_data$family_size &lt;- full_data$SibSp + full_data$Parch + 1

# 視覺化 `family_size` 與 `Survived` 之間的關係
library(gridExtra)
gg1 &lt;- ggplot(full_data[full_data$Set == &quot;Train&quot;, ], aes(x = family_size, fill = factor(Survived))) +
  geom_bar(stat = &quot;count&quot;, position = &quot;dodge&quot;) +
  scale_x_continuous(breaks = c(1:11)) +
  xlab(&quot;Family Size&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Passenger Survival Counts by Family Size&quot;) +
  theme(legend.position = &quot;bottom&quot;,
        plot.title = element_text(size = 15, hjust = 0.5)) +
  scale_fill_discrete(guide = guide_legend(title = &quot;survived&quot;),
                      labels = c(&quot;NO&quot;, &quot;YES&quot;)) +
  geom_text(stat = &quot;count&quot;, aes(label = ..count..),
            position = position_dodge(width = 0.9), vjust = -0.25, size = 3)
gg2 &lt;- ggplot(full_data[full_data$Set == &quot;Train&quot;, ], aes(x = family_size, fill = factor(Survived))) +
  geom_bar(stat = &quot;count&quot;, position = &quot;fill&quot;) +
  scale_x_continuous(breaks = c(1:11)) +
  scale_y_continuous(labels = scales::percent) +
  xlab(&quot;Family Size&quot;) +
  ylab(&quot;Percentage&quot;) +
  ggtitle(&quot;Passenger Survival Rates by Family Size&quot;) +
  theme(legend.position = &quot;bottom&quot;,
        plot.title = element_text(size = 15, hjust = 0.5)) +
  scale_fill_discrete(guide = guide_legend(title = &quot;survived&quot;),
                      labels = c(&quot;NO&quot;, &quot;YES&quot;))
grid.arrange(gg1, gg2, ncol=2)</code></pre>
<p><img src="/post/2017-12-28-Titanic-Machine-Learning-from-Disaster_files/figure-html/unnamed-chunk-9-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>上圖的視覺化告訴我們乘客的旅行人數是會影響生存情況的，不管是從「依照家庭人口數來計算倖存者的數量 (左圖)」還是從「依照家庭人口數來劃分倖存者的比例 (右圖)」的角度來看存活性，都可以發現 <strong>1 &lt; 家庭人口 &lt; 5</strong> 存活的可能性比 <strong>家庭人口 = 1</strong> 和 <strong>家庭人口 &gt; 4</strong> 來的高。</p>
<p>另外，還可以再發現家庭人口為 1 的人數佔的好高！他們不是和家人一起旅遊，有可能是和朋友、情人、親友、傭人等人一起旅行，或者是獨自旅行。</p>
<p>所以呢只知道是否為家庭旅遊還不夠，我們再做更進階的探勘：一起購票的家庭或是團體似乎有相同的船票編號，利用 <strong>Ticket</strong> 變數 (船票編號) 來辨識乘客是獨自旅行還是團體旅行。最後再用視覺化來觀察一下！</p>
<pre class="r"><code># 將 `family_size` 變數分成 &quot;非家庭旅行&quot;、&quot;小家庭旅行&quot; 和 &quot;大家庭旅行&quot; 三個層面，存放在新建立的變數 `family_type`
full_data$family_type[full_data$family_size == 1] &lt;- &quot;非家庭旅行&quot;
full_data$family_type[full_data$family_size &gt; 1 &amp; full_data$family_size &lt; 5] &lt;- &quot;小家庭旅行&quot;
full_data$family_type[full_data$family_size &gt; 4] &lt;- &quot;大家庭旅行&quot;
full_data$family_type &lt;- factor(full_data$family_type)

# 使用 `Ticket` 變數製作 `group_size` 變數 (團體旅遊人數)
library(magrittr)
library(dplyr)
full_data &lt;- full_data %&gt;%
  mutate(travel_group = match(Ticket, unique(Ticket)))

full_data$travel_group &lt;- factor(full_data$travel_group)

full_data &lt;- full_data %&gt;%
  group_by(travel_group) %&gt;%
  mutate(group_size = n())

# 將 `非家庭旅行` 及 `團體旅遊人數為 1 人` 的乘客認定為 &quot;獨自旅行&quot;
full_data$family_type &lt;- as.character(full_data$family_type)
full_data[full_data$family_type == &quot;非家庭旅行&quot; &amp; full_data$group_size == 1, ]$family_type &lt;- &quot;獨自旅行&quot;
full_data$family_type &lt;- factor(full_data$family_type)

# 視覺化 `family_type` 與 `Survived` 之間的關係
library(vcd)
mosaicplot(full_data[full_data$Set == &quot;Train&quot;, ]$family_type ~ full_data[full_data$Set == &quot;Train&quot;, ]$Survived,
           main=&quot;Passenger Survival by Family Type&quot;,
           shade = FALSE, color = TRUE,
           xlab = &quot;Family Type&quot;, ylab = &quot;Survived&quot;,
           cex.axis = 1)</code></pre>
<p><img src="/post/2017-12-28-Titanic-Machine-Learning-from-Disaster_files/figure-html/unnamed-chunk-10-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>註：視覺化中的<strong>非家庭旅行</strong>包括朋友、情人、親友、傭人等人一起旅行。</p>
<p>可觀察到大多數的乘客都是 “獨自旅行” 的，但存活的比例似乎不太高，反而是 “小家庭旅行” 存活的機會大於 50%，</p>
</div>
</div>
<div id="-impute-missing-value" class="section level1">
<h1><span class="header-section-number">3</span> 遺漏值處理 (Impute Missing Value)</h1>
<p><strong>———————————————————遺漏值：Embarked———————————————————-</strong></p>
<pre class="r"><code># 看一下 `Embarked` 2 個空值的觀測值
data.frame(full_data[full_data$Embarked == &quot;&quot;, ])</code></pre>
<pre><code>##   PassengerId Survived Pclass                                      Name
## 1          62        1      1                       Icard, Miss. Amelie
## 2         830        1      1 Stone, Mrs. George Nelson (Martha Evelyn)
##      Sex Age SibSp Parch Ticket Fare Cabin Embarked   Set Title Child
## 1 female  38     0     0 113572   80   B28          Train  Miss Adult
## 2 female  62     0     0 113572   80   B28          Train   Mrs Adult
##   identity family_size family_type travel_group group_size
## 1    Woman           1  非家庭旅行           61          2
## 2    Woman           1  非家庭旅行           61          2</code></pre>
<p>可以觀察到編號 62 和 830 的乘客資訊很相似，差別只在於年紀的不同而已，同樣支付了 $80 票價，且都是 Upper 艙等，但都不知道是從哪個港口上船的。我們假設相同票價的乘客是在同一個港口上船的，可以用 <strong>票價 Fare</strong> 和 <strong>艙等 Pclass</strong> 來推估乘客會從哪一個 <strong>港口出發 Embarked</strong>。</p>
<pre class="r"><code># 視覺化 `Fare`、`Embarked` 與 `Pclass` 之間的關係
ggplot(full_data[full_data$Embarked != &quot;&quot;, ], aes(x = Embarked, y = Fare, fill = Pclass)) +
  geom_boxplot() +
  geom_hline(aes(yintercept = 80),
             colour = &quot;#9933ff&quot;, lty = 2, size = 2) +
  scale_y_continuous(labels = scales::dollar) + 
  geom_text(aes(3.4, 80, label = &quot;$80&quot;, vjust = -1), size = 6, colour = &quot;#9933ff&quot;) +
  scale_fill_discrete(guide = guide_legend(title = &quot;Pclass&quot;),
                      labels = c(&quot;Upper&quot;, &quot;Middle&quot;, &quot;Lower&quot;)) +
  scale_x_discrete(labels = c(&quot;Cherbourg&quot;, &quot;Queenstown&quot;, &quot;Southampton&quot;))</code></pre>
<p><img src="/post/2017-12-28-Titanic-Machine-Learning-from-Disaster_files/figure-html/unnamed-chunk-12-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>編號 62 和 830 乘客支付的費用 $80 洽好和從 Cherbourg 港口出發的 Upper 艙等乘客中位票價一樣，因此他們很有可能是從 Cherbourg 港口上船的，我們可以用 “C” 替換空值。</p>
<pre class="r"><code># 填補 `Embarked` 遺漏值
full_data$Embarked &lt;- as.character(full_data$Embarked)
full_data[full_data$Embarked == &quot;&quot;, ]$Embarked &lt;- &quot;C&quot;
full_data$Embarked &lt;- factor(full_data$Embarked)</code></pre>
<p><strong>————————————————————-遺漏值：Fare————————————————————–</strong></p>
<pre class="r"><code># 看一下遺漏 `Fare` 的觀測值
data.frame(full_data[is.na(full_data$Fare), ])</code></pre>
<pre><code>##   PassengerId Survived Pclass               Name  Sex  Age SibSp Parch
## 1        1044       NA      3 Storey, Mr. Thomas male 60.5     0     0
##   Ticket Fare Cabin Embarked  Set Title Child identity family_size
## 1   3701   NA              S Test    Mr Adult      Man           1
##   family_type travel_group group_size
## 1    獨自旅行          779          1</code></pre>
<p>可以知道編號 1044 的乘客是從 Southampton 港口出發的 Lower 艙等，但不知道票價是多少。我們可以用剛剛填補登船港口遺漏值的思維，用<strong>港口出發 Embarked</strong> 地點和<strong>艙等 Pclass</strong> 來推估乘客會落在哪一個<strong>票價 Fare</strong>。</p>
<pre class="r"><code># 視覺化從 Southampton 港口出發的 Lower 艙等乘客的票價
ggplot(full_data[full_data$Pclass == &quot;3&quot; &amp; full_data$Embarked == &quot;S&quot;, ], aes(x = Fare)) +
  geom_density(fill = &quot;#0080ff&quot;, alpha=0.3) +
  geom_vline(aes(xintercept = median(Fare, na.rm = TRUE)),  # Pclass=3 &amp; Embarked=&quot;S&quot;的median Fare
             colour = &quot;red&quot;, lty = 2, size = 1) +
  scale_x_continuous(labels = scales::dollar) +
  xlab(&quot;Fare&quot;) +
  ylab(&quot;Density&quot;) +
  ggtitle(&quot;從 Southampton 港口出發的 Lower 艙等乘客的票價&quot;) +
  theme(plot.title = element_text(size = 15, hjust = 0.5),
        panel.grid.minor = element_blank())</code></pre>
<p><img src="/post/2017-12-28-Titanic-Machine-Learning-from-Disaster_files/figure-html/unnamed-chunk-15-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>從 Southampton 港口出發的 Lower 艙等乘客的票價大部分分布在 $0~$20 之間，資料呈現右偏分配，存在比較大的離群值，由於中位數較平均數不容易受離群值的影響，因此標一條紅色虛線表示中位數來觀察一下，意外的發現票價的中位數恰好為眾數！我們可以將編號 1044 乘客的遺漏值 <strong>Fare</strong> 用中位數來替換，對於這個乘客付出這樣的價錢似乎也蠻合理的。</p>
<pre class="r"><code># 依照乘客所屬 `Pclass` 與 `Embarked` 的中位數替換票價遺漏值
full_data[is.na(full_data$Fare), ]$Fare &lt;- median(full_data[full_data$Pclass == &quot;3&quot; &amp; full_data$Embarked == &quot;S&quot;, ]$Fare, na.rm = TRUE)</code></pre>
<p><strong>————————————————————-遺漏值：Age————————————————————–</strong></p>
<pre class="r"><code># 視覺化 `Title` 在不同的 `Pclass` 中與 `Age` 之間的關係
ggplot(full_data, aes(x = Title, y = Age, fill = Title)) +
  geom_boxplot() +
  facet_wrap(~ Pclass, labeller = label_both) +
  stat_summary(fun.y = mean, colour = &quot;white&quot;, geom = &quot;point&quot;, size = 2, show_guide = FALSE)</code></pre>
<p><img src="/post/2017-12-28-Titanic-Machine-Learning-from-Disaster_files/figure-html/unnamed-chunk-17-1.png" width="864" style="display: block; margin: auto;" /></p>
<p>發現艙等等級會隨著年齡而變化，年齡越大的乘客購買艙等的等級就越高。在 Pclass = 1 (Upper艙等) 乘客的年齡普遍都比較大，且 Title 為 Master 乘客的年齡都頗小的。</p>
<p>資料中存在離群值，因此標一個白色圓點表示平均值，來觀察平均值是否受離群值影響很大。視覺化顯示平均值和中位數兩者間的差異沒有到很大，因此決定把遺漏值 <strong>Age</strong> 依照 <strong>Title</strong> 與 <strong>Pclass</strong> 的平均年齡進行填補。</p>
<pre class="r"><code># 結合 `Title` 與 `Pclass` 計算平均年齡
mean_age_by_Title_and_Pclass &lt;- full_data %&gt;%
  group_by(Title, Pclass) %&gt;%
  summarise(mean_age = round(mean(Age, na.rm = TRUE), 2))
mean_age_by_Title_and_Pclass</code></pre>
<pre><code>## # A tibble: 15 x 3
## # Groups:   Title [?]
##      Title Pclass mean_age
##     &lt;fctr&gt; &lt;fctr&gt;    &lt;dbl&gt;
##  1  Master      1     6.98
##  2  Master      2     2.76
##  3  Master      3     6.09
##  4    Miss      1    30.13
##  5    Miss      2    20.87
##  6    Miss      3    17.36
##  7      Mr      1    41.45
##  8      Mr      2    32.35
##  9      Mr      3    28.32
## 10     Mrs      1    42.93
## 11     Mrs      2    33.52
## 12     Mrs      3    32.33
## 13   Noble      1    42.00
## 14 Officer      1    49.29
## 15 Officer      2    40.70</code></pre>
<pre class="r"><code># 視覺化 Age 為遺漏值的乘客 `Title` 與 `Pclass` 之間的關係
ggplot(full_data[is.na(full_data$Age), ], aes(x = Title, fill = Pclass)) +
  geom_bar(stat = &quot;count&quot;, position = &quot;dodge&quot;) +
  xlab(&quot;Title&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Missing Age Passenger Pclass Counts by Title&quot;) +
  theme(legend.position = &quot;right&quot;,
        plot.title = element_text(size = 15, hjust = 0.5)) +
  scale_fill_discrete(guide = guide_legend(title = &quot;Pclass&quot;),
                      labels = c(&quot;1st = Upper&quot;, &quot;2nd = Middle&quot;, &quot;3rd = Lower&quot;)) +
  geom_text(stat = &quot;count&quot;, aes(label = ..count..),
            position = position_dodge(width = 0.9), vjust = -0.25, size = 3)</code></pre>
<p><img src="/post/2017-12-28-Titanic-Machine-Learning-from-Disaster_files/figure-html/unnamed-chunk-18-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>可注意到在 Age 為遺漏值的乘客中，並不是每個 Title 類別在三個艙等都有遺漏值，例如 Title 為 Master 的乘客中 Age 為遺漏值的只有在 Lower 艙等而已，Title 為 Noble 的乘客中 Age 皆無遺漏值，以此類推…。因此在填補 Age 遺漏值時要與 mean_age_by_Title_and_Pclass 的順序對應好。</p>
<pre class="r"><code># 依照 `Title` 與 `Pclass` 的平均年齡替換年齡遺漏值
full_data[is.na(full_data$Age) &amp; full_data$Title == &quot;Master&quot; &amp; full_data$Pclass == &quot;3&quot;, ]$Age &lt;- mean_age_by_Title_and_Pclass$mean_age[3]
full_data[is.na(full_data$Age) &amp; full_data$Title == &quot;Miss&quot; &amp; full_data$Pclass == &quot;1&quot;, ]$Age &lt;- mean_age_by_Title_and_Pclass$mean_age[4]
full_data[is.na(full_data$Age) &amp; full_data$Title == &quot;Miss&quot; &amp; full_data$Pclass == &quot;2&quot;, ]$Age &lt;- mean_age_by_Title_and_Pclass$mean_age[5]
full_data[is.na(full_data$Age) &amp; full_data$Title == &quot;Miss&quot; &amp; full_data$Pclass == &quot;3&quot;, ]$Age &lt;- mean_age_by_Title_and_Pclass$mean_age[6]
full_data[is.na(full_data$Age) &amp; full_data$Title == &quot;Mr&quot; &amp; full_data$Pclass == &quot;1&quot;, ]$Age &lt;- mean_age_by_Title_and_Pclass$mean_age[7]
full_data[is.na(full_data$Age) &amp; full_data$Title == &quot;Mr&quot; &amp; full_data$Pclass == &#39;2&#39;, ]$Age &lt;- mean_age_by_Title_and_Pclass$mean_age[8]
full_data[is.na(full_data$Age) &amp; full_data$Title == &quot;Mr&quot; &amp; full_data$Pclass == &quot;3&quot;, ]$Age &lt;- mean_age_by_Title_and_Pclass$mean_age[9]
full_data[is.na(full_data$Age) &amp; full_data$Title == &quot;Mrs&quot; &amp; full_data$Pclass == &quot;1&quot;, ]$Age &lt;- mean_age_by_Title_and_Pclass$mean_age[10]
full_data[is.na(full_data$Age) &amp; full_data$Title == &quot;Mrs&quot; &amp; full_data$Pclass == &quot;2&quot;, ]$Age &lt;- mean_age_by_Title_and_Pclass$mean_age[11]
full_data[is.na(full_data$Age) &amp; full_data$Title == &quot;Mrs&quot; &amp; full_data$Pclass == &quot;3&quot;, ]$Age &lt;- mean_age_by_Title_and_Pclass$mean_age[12]
full_data[is.na(full_data$Age) &amp; full_data$Title == &quot;Officer&quot; &amp; full_data$Pclass == &quot;1&quot;, ]$Age &lt;- mean_age_by_Title_and_Pclass$mean_age[14]

# 完成年齡遺漏值填補後，對之前還沒有辨識到 `identity` 的乘客再做一次辨識
full_data$identity &lt;- as.character(full_data$identity)
full_data$identity[full_data$Age &gt;= 15 &amp; full_data$Sex == &quot;male&quot;] &lt;- &quot;Man&quot;
full_data$identity[full_data$Age &gt;= 15 &amp; full_data$Sex == &quot;female&quot;] &lt;- &quot;Woman&quot;
full_data$identity[full_data$Age &lt; 15 &amp; full_data$Sex == &quot;male&quot;] &lt;- &quot;Boy&quot;
full_data$identity[full_data$Age &lt; 15 &amp; full_data$Sex == &quot;female&quot;] &lt;- &quot;Girl&quot;
full_data$identity &lt;- factor(full_data$identity)

# 完成年齡遺漏值填補後，對之前還沒有辨識到 `Child` 的乘客再做一次辨識
full_data$Child &lt;- as.character(full_data$Child)
full_data$Child[full_data$Age &lt; 15] &lt;- &quot;Child&quot;
full_data$Child[full_data$Age &gt;= 15] &lt;- &quot;Adult&quot;
full_data$Child &lt;- factor(full_data$Child)</code></pre>
<p>檢查 titanic 資料集是否還有遺漏值的存在。</p>
<pre class="r"><code># 計算遺漏值數量
sum(is.na(full_data %&gt;% select(-Survived)))</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code># 填補遺漏值後的 summary
summary(full_data)</code></pre>
<pre><code>##   PassengerId      Survived      Pclass 
##  Min.   :   1   Min.   :0.0000   1:323  
##  1st Qu.: 328   1st Qu.:0.0000   2:277  
##  Median : 655   Median :0.0000   3:709  
##  Mean   : 655   Mean   :0.3838          
##  3rd Qu.: 982   3rd Qu.:1.0000          
##  Max.   :1309   Max.   :1.0000          
##                 NA&#39;s   :418             
##                                Name          Sex           Age       
##  Connolly, Miss. Kate            :   2   female:466   Min.   : 0.17  
##  Kelly, Mr. James                :   2   male  :843   1st Qu.:21.00  
##  Abbing, Mr. Anthony             :   1                Median :28.32  
##  Abbott, Mr. Rossmore Edward     :   1                Mean   :29.51  
##  Abbott, Mrs. Stanton (Rosa Hunt):   1                3rd Qu.:36.50  
##  Abelson, Mr. Samuel             :   1                Max.   :80.00  
##  (Other)                         :1301                               
##      SibSp            Parch            Ticket          Fare        
##  Min.   :0.0000   Min.   :0.000   CA. 2343:  11   Min.   :  0.000  
##  1st Qu.:0.0000   1st Qu.:0.000   1601    :   8   1st Qu.:  7.896  
##  Median :0.0000   Median :0.000   CA 2144 :   8   Median : 14.454  
##  Mean   :0.4989   Mean   :0.385   3101295 :   7   Mean   : 33.276  
##  3rd Qu.:1.0000   3rd Qu.:0.000   347077  :   7   3rd Qu.: 31.275  
##  Max.   :8.0000   Max.   :9.000   347082  :   7   Max.   :512.329  
##                                   (Other) :1261                    
##              Cabin      Embarked     Set                Title    
##                 :1014   C:272    Length:1309        Master : 61  
##  C23 C25 C27    :   6   Q:123    Class :character   Miss   :264  
##  B57 B59 B63 B66:   5   S:914    Mode  :character   Mr     :757  
##  G6             :   5                               Mrs    :198  
##  B96 B98        :   4                               Noble  :  4  
##  C22 C26        :   4                               Officer: 25  
##  (Other)        : 271                                            
##    Child       identity    family_size         family_type   travel_group 
##  Adult:1192   Boy  : 66   Min.   : 1.000   大家庭旅行: 82   149    :  11  
##  Child: 117   Girl : 51   1st Qu.: 1.000   小家庭旅行:437   59     :   8  
##               Man  :777   Median : 1.000   非家庭旅行:127   73     :   8  
##               Woman:415   Mean   : 1.884   獨自旅行  :663   14     :   7  
##                           3rd Qu.: 2.000                    25     :   7  
##                           Max.   :11.000                    50     :   7  
##                                                             (Other):1261  
##    group_size    
##  Min.   : 1.000  
##  1st Qu.: 1.000  
##  Median : 1.000  
##  Mean   : 2.102  
##  3rd Qu.: 3.000  
##  Max.   :11.000  
## </code></pre>
<p>titanic 資料集中的 <strong>Age</strong>、<strong>Fare</strong>、<strong>Embarked</strong> 都沒有遺漏值的存在了，可以進行後續的建模啦！</p>
</div>
<div id="-training-a-model" class="section level1">
<h1><span class="header-section-number">4</span> 訓練模型 (Training a Model)</h1>
<p>使用機器學習的<strong>隨機森林 (randomForest)</strong> 演算法在訓練資料上建構我們的模型。</p>
<div id="-variable-selection" class="section level2">
<h2><span class="header-section-number">4.1</span> 變數選擇 (Variable Selection)</h2>
<p>回顧一下「特徵工程 (Feature Engineering)」小節，我們利用 titanic 資料集原始存在的變數衍生出很多新的變數，也發現那些衍生出來的變數都對 <strong>Survived</strong> 有一定的影響力，而在選擇模型的預測變數時，有重疊的變數我們將擇一選擇。變數選擇結果如下表：</p>
<table>
<thead>
<tr class="header">
<th>原始變數</th>
<th>衍生變數</th>
<th>變數選擇</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pclass</td>
<td></td>
<td>Pclass</td>
</tr>
<tr class="even">
<td>Name</td>
<td>Title</td>
<td>Title</td>
</tr>
<tr class="odd">
<td>Sex</td>
<td></td>
<td>Sex</td>
</tr>
<tr class="even">
<td>Age</td>
<td>Child</td>
<td>Child</td>
</tr>
<tr class="odd">
<td>Sex &amp; Age</td>
<td>identity</td>
<td></td>
</tr>
<tr class="even">
<td>SibSp &amp; Parch</td>
<td>family_size、family_type</td>
<td>family_type</td>
</tr>
<tr class="odd">
<td>Ticket</td>
<td>group_size</td>
<td>group_size</td>
</tr>
<tr class="even">
<td>Fare</td>
<td></td>
<td>Fare</td>
</tr>
<tr class="odd">
<td>Embarked</td>
<td></td>
<td>Embarked</td>
</tr>
</tbody>
</table>
<p><strong>PassengerId</strong> 變數基本上每個乘客都不一樣，<strong>Cabin</strong> 變數的遺漏值缺失很嚴重，所以在訓練模型時不考慮這兩個變數。</p>
</div>
<div id="-building-a-classification-model" class="section level2">
<h2><span class="header-section-number">4.2</span> 建立分類模型 (Building a Classification Model)</h2>
<pre class="r"><code>full_data$Survived &lt;- factor(full_data$Survived, levels = c(&quot;1&quot;, &quot;0&quot;))

# 將 train 資料提取出來作為訓練模型的資料
modeling_data &lt;- full_data[full_data$Set == &quot;Train&quot;, ]

# 找出決策樹進行分裂時所選擇的特徵個數之最佳值 (mtry)
library(randomForest)
model_err_rate = 1
for(i in 1:8)  # 8 為 Pclass, Sex, Child, Fare, Embarked, Title, family_type, group_size
{
  set.seed(754)
  result = randomForest(Survived ~ Pclass + Sex + Child + Fare + Embarked + Title + family_type + group_size, data = modeling_data, mtry = i, ntree = 500)
  model_err_rate[i] = mean(result$err.rate)
}
mtry_value = which.min(model_err_rate)

# 建立 randomForest 分類器
set.seed(754)
rfModel &lt;- randomForest(Survived ~ Pclass + Sex + Child + Fare + Embarked + Title + family_type + group_size, data = modeling_data, mtry = mtry_value, ntree = 500)</code></pre>
</div>
<div id="-variable-importance" class="section level2">
<h2><span class="header-section-number">4.3</span> 變數的重要性 (Variable Importance)</h2>
<pre class="r"><code># plot variable importance
varImpPlot(rfModel, main = &quot;Importance of Variables&quot;)</code></pre>
<p><img src="/post/2017-12-28-Titanic-Machine-Learning-from-Disaster_files/figure-html/unnamed-chunk-22-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code># output variable importance
round(importance(rfModel), 2)</code></pre>
<pre><code>##             MeanDecreaseGini
## Pclass                 28.40
## Sex                    54.76
## Child                   6.78
## Fare                   46.56
## Embarked                8.34
## Title                  73.16
## family_type            20.42
## group_size             21.39</code></pre>
<p>上面結果顯示了各個變數的節點純度，也就是說變數在分資料群時是否有判斷性，值愈高表示該變數對於模型的判別影響力愈大，可以作為往後利用其他演算法進行建模時刪減變數的依據。結果令我很訝異…從乘客姓名衍生出來的 <strong>Title</strong> 變數竟然最為重要！</p>
</div>
</div>
<div id="-evaluating-model-performance" class="section level1">
<h1><span class="header-section-number">5</span> 衡量模型表現 (Evaluating Model Performance)</h1>
<div id="-model-error" class="section level2">
<h2><span class="header-section-number">5.1</span> 模型錯誤率 (Model Error)</h2>
<pre class="r"><code>rfModel</code></pre>
<pre><code>## 
## Call:
##  randomForest(formula = Survived ~ Pclass + Sex + Child + Fare +      Embarked + Title + family_type + group_size, data = modeling_data,      mtry = mtry_value, ntree = 500) 
##                Type of random forest: classification
##                      Number of trees: 500
## No. of variables tried at each split: 2
## 
##         OOB estimate of  error rate: 16.05%
## Confusion matrix:
##     1   0 class.error
## 1 246  96   0.2807018
## 0  47 502   0.0856102</code></pre>
<p>對 OOB 樣本進行預測，錯誤率為 16.05%。 註：out-of-bag (OOB) 為每次抽樣中的袋外樣本</p>
<p>從混淆矩陣 (Confusion Matrix) 可看出：</p>
<ul>
<li>模型將原本為 1 (存活) 的正確預測為 1 (存活) 的有 246 筆</li>
<li>模型將原本為 1 (存活) 的錯誤預測為 0 (死亡) 的有 96 筆</li>
<li>1 (存活) 的誤判率有 28.07%</li>
<li>模型將原本為 0 (死亡) 的正確預測為 0 (死亡) 的有 502 筆</li>
<li>模型將原本為 0 (死亡) 的錯誤預測為 1 (存活) 的有 47 筆</li>
<li>0 (死亡) 的誤判率有 8.56%</li>
</ul>
<pre class="r"><code>plot(rfModel, col = c(&quot;#000000&quot;, &quot;#005ce6&quot;, &quot;#ff0000&quot;), lwd = 1.5,
     ylim=c(0,0.4), main = &quot;Error Rate of rfModel&quot;)
legend(&quot;topright&quot;, legend = colnames(rfModel$err.rate),
       col = c(&quot;#000000&quot;, &quot;#005ce6&quot;, &quot;#ff0000&quot;), fill = c(&quot;#000000&quot;, &quot;#005ce6&quot;, &quot;#ff0000&quot;))</code></pre>
<p><img src="/post/2017-12-28-Titanic-Machine-Learning-from-Disaster_files/figure-html/unnamed-chunk-24-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>上圖顯示了 randomForest 模型的錯誤率，黑線顯示總體錯誤率低於 20%。藍線和紅線分別顯示 “存活” 和 “死亡” 的錯誤率，可以看到死亡的預測效果比預測存活還要好，而且預測存活的錯誤率比總體錯誤率還要高，為什麼會這樣呢？這是一個值得思考的問題！</p>
</div>
<div id="-model-accuracy" class="section level2">
<h2><span class="header-section-number">5.2</span> 模型準確度 (Model Accuracy)</h2>
<pre class="r"><code># 計算 accuracy
prediction &lt;- predict(rfModel)
confusion_matrix &lt;- table(modeling_data$Survived, prediction)
accuracy &lt;- sum(diag(confusion_matrix)) / sum(confusion_matrix)
accuracy</code></pre>
<pre><code>## [1] 0.8395062</code></pre>
</div>
<div id="roc--roc-curve" class="section level2">
<h2><span class="header-section-number">5.3</span> ROC 曲線 (ROC Curve)</h2>
<pre class="r"><code># ROC Curve
library(ROCR)
probabilities &lt;- predict(rfModel, type = &quot;prob&quot;)[,1]
pred &lt;- prediction(probabilities, labels = modeling_data$Survived)
perf &lt;- performance(pred, &quot;tpr&quot;, &quot;fpr&quot;)
plot(perf)</code></pre>
<p><img src="/post/2017-12-28-Titanic-Machine-Learning-from-Disaster_files/figure-html/unnamed-chunk-26-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code># 計算 AUC (計算 ROC 曲線底下的面積)
perf &lt;- performance(pred, &quot;auc&quot;)
perf@y.values[[1]]</code></pre>
<pre><code>## [1] 0.8787082</code></pre>
</div>
</div>
<div id="making-our-prediction" class="section level1">
<h1><span class="header-section-number">6</span> Making our prediction</h1>
<p>是時候來預測了！現在將使用上面所建立好的 RandomForest 模型應用在 titanic 中的測試資料 <strong>test.csv</strong> 來預測 <strong>Survived</strong>。</p>
<pre class="r"><code># 將 test 資料提取出來做預測
predict_data &lt;- full_data[full_data$Set == &quot;Test&quot;, ]

# 對 test 資料做預測
predicted &lt;- predict(rfModel, newdata = predict_data)

# 依照競賽的 Submission File Format，產出 2 個欄位的檔案：PassengerId、Survived (predicted)
solution &lt;- data.frame(PassengerId = predict_data[, &quot;PassengerId&quot;], Survived = predicted)

# 看一下 solution 的前 10 筆資料
head(solution, n = 10)</code></pre>
<pre><code>##    PassengerId Survived
## 1          892        0
## 2          893        1
## 3          894        0
## 4          895        0
## 5          896        1
## 6          897        0
## 7          898        1
## 8          899        0
## 9          900        1
## 10         901        0</code></pre>
<pre class="r"><code># 將 solution 匯出為 csv 檔案
write.csv(solution, file = &quot;result/r_randomForest_submission.csv&quot;, row.names = FALSE, quote = FALSE)</code></pre>
</div>

      </article>

      <ul class="pager blog-pager">
        
        
          <li class="next">
            <a href="/post/2017-12-29-%E4%BD%BF%E7%94%A8jupyter-notebook%E9%81%8B%E8%A1%8Cr%E8%AA%9E%E8%A8%80%E7%92%B0%E5%A2%83/" data-toggle="tooltip" data-placement="top" title="使用 Jupyter Notebook 運行 R 語言環境">Next Post &rarr;</a>
          </li>
        
      </ul>


      
        
        
      

    </div>
  </div>
</div>

    <footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center footer-links">
          
              <li>
                <a href="mailto:carolchency@gmail.com" title="Email me">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://www.facebook.com/chiayinchen526" title="Facebook">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://github.com/chiayinchen" title="GitHub">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://linkedin.com/in/chiayinchen" title="LinkedIn">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://www.instagram.com/cy_neihu" title="Instagram">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
          
        </ul>
        <p class="credits copyright text-muted">
          
            
              <a href="https://medium.com/@chiayinchen">© Carol Chen</a>
            
          

          &nbsp;&bull;&nbsp;
          2017

          
            &nbsp;&bull;&nbsp;
            <a href="/">Chia-Yin Chen</a>
          
        </p>
        
        <p class="credits theme-by text-muted">
          <a href="http://gohugo.io">Hugo v0.54.0</a> powered &nbsp;&bull;&nbsp; Theme by <a href="http://deanattali.com/beautiful-jekyll/">Beautiful Jekyll</a> adapted to <a href="https://github.com/halogenica/beautifulhugo">Beautiful Hugo</a>
          
        </p>
      </div>
    </div>
  </div>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js" integrity="sha384-/y1Nn9+QQAipbNQWU65krzJralCnuOasHncUFXGkdwntGeSvQicrYkiUBwsgUqc1" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/contrib/auto-render.min.js" integrity="sha384-dq1/gEHSxPZQ7DdrM82ID4YVol9BYyU7GbWlIwnwyPzotpoc57wDw/guX8EaYGPx" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/main.js"></script>
<script src="/js/highlight.min.js"></script>
<script> hljs.initHighlightingOnLoad(); </script><script> renderMathInElement(document.body); </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js" integrity="sha256-UplRCs9v4KXVJvVY+p+RSo5Q4ilAUXh7kpjyIP5odyc=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js" integrity="sha256-PWHOlUzc96pMc8ThwRIXPn8yH4NOLu42RQ0b9SpnpFk=" crossorigin="anonymous"></script>
<script src="/js/load-photoswipe.js"></script>




  </body>
</html>

